# Generated by Django 4.2.1 on 2023-05-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affichageImage', '0003_remove_image_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='titre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
