# Generated by Django 4.2.1 on 2023-05-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affichageImage', '0004_image_titre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='photos',
            field=models.ImageField(null=True, upload_to='images/%y'),
        ),
    ]
