# Generated by Django 4.2.1 on 2023-05-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affichageImage', '0005_remove_image_photo_image_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photos',
        ),
        migrations.AddField(
            model_name='image',
            name='imgs',
            field=models.ImageField(null=True, upload_to='images/%y'),
        ),
    ]
