# Generated by Django 4.2.1 on 2023-05-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affichageImage', '0006_remove_image_photos_image_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imgs',
            field=models.ImageField(null=True, upload_to='pht/%y'),
        ),
    ]
